from L import ListaDE

print(__name__)

if __name__ == '__main__':
    Lista = ListaDE()
    Lista.inserirFim(19)
    Lista.inserirFim(20)
    Lista.inserirFrente(2)
    Lista.inserirFrente(1)
    print('-----------------------------')
    Lista.contem(1)
    Lista.contem(2)
    Lista.contem(19)
    Lista.contem(20)
    Lista.contem(33)
    Lista.posicaoDe(1)
    Lista.posicaoDe(2)
    Lista.posicaoDe(19)
    Lista.posicaoDe(20)
    Lista.posicaoDe(33)
    print('-----------------------------')
    Lista.inserirNaPosicao(3, 4)
    Lista.posicaoDe(4)
    print('-----------------------------')
    print(Lista.elementos())
    Lista.posicaoDe(20)
    Lista.excluirUlt()
    print(Lista.elementos())
    Lista.posicaoDe(20)
    print('-----------------------------')
    Lista.posicaoDe(1)
    Lista.excluirPrim()
    print(Lista.elementos())
    Lista.contem(1)
    print('-----------------------------')
    Lista.excluirElem(2)
    Lista.contem(2)
    print('-----------------------------')
    Lista.posicaoDe(1)
    Lista.posicaoDe(2)
    Lista.posicaoDe(4)
    Lista.posicaoDe(19)
    Lista.posicaoDe(20)
    Lista.posicaoDe(33)
    print('-----------------------------')
    Lista.excluirDaPos(1)
    Lista.contem(4)
    print('-----------------------------')
    print(Lista.elementos())
    Lista.posicaoDe(19)
    Lista.excluirAtual()
    Lista.posicaoDe(19)
    print('-----------------------------')
